version: '3.12-slim'

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile  # Custom Nginx Dockerfile
    container_name: proxy
    image: gaicr.azurecr.io/test/nginx
    ports:
      - "80:80"     # Expose Nginx on port 80 to the public
    depends_on:
      - nextjs    # Ensure frontend and backend are running before Nginx starts
      - fastapi
    networks:
      - dev-network

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    image: gaicr.azurecr.io/test/nextjs
    volume:
      - ${WEBAPP_STORAGE_HOME}/nextjs:/app
      - ${WEBAPP_STORAGE_HOME}/app/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - dev-network

  fastapi:
    build:
      context: .
    image: gaicr.azurecr.io/test/fastapi
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6380
      - NEXT_PUBLIC_API_KEY=${static_bearer_secret_key}
    depends_on:
      - mongodb
      - redis
    networks:
      - dev-network

  mongodb:
    image: gaicr.azurecr.io/test/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bringthemhome
      - MONGO_INITDB_ROOT_PASSWORD=${mongodb_password}
    ports:
      - "10255:10255" # for testing purposes you can expose the MongoDB port
    volumes:
      - mongodb_data:/data/db
    networks:
      - dev-network


  redis:
    image: gaicr.azurecr.io/test/redis
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: ["redis-server", "--save", "", "--maxmemory", "1024mb", "--maxmemory-policy", "allkeys-lru"]

volumes:
  mongodb_data:
  redis_data:

networks:
  dev-network:
    driver: bridge