version: '3.12-slim'

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile  # Custom Nginx Dockerfile
    container_name: proxy
#    image: usmslm102/nginx-proxy:latest
    ports:
      - "3000"     # Expose Nginx on port 80 to the public
    depends_on:
      - nextjs    # Ensure frontend and backend are running before Nginx starts
      - fastapi
    networks:
      - dev-network

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - dev-network

  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_API_KEY=${static_bearer_secret_key}
    depends_on:
      - mongodb
      - redis
    networks:
      - dev-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bringthemhome
      - MONGO_INITDB_ROOT_PASSWORD=${mongodb_password}
    ports:
      - "10255:10255" # for testing purposes you can expose the MongoDB port
    volumes:
      - mongodb_data:/data/db
    networks:
      - dev-network

  redis:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
  redis_data:

networks:
  dev-network:
    driver: bridge